---
title: "Datacamp_Cleaning Data in R_Tidying data"
author: "dizhen"
date: "2019/4/4"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Introduction to tidyr

1. Summary of key tidyr functions

gather() - Gather columns into key-value pairs (wide -> long)

spread() - Spread key-value pairs into columns (long -> wide)

separate() - Separate one column into multiple

unite() - Unite multiple columns into one

```{r}
library("tidyr")
wide_df <- data.frame(col = c("X","Y"), A = c(1,4), B = c(2,5), C= c(3,6))

# Gather the columns of wide_df
long_df<-gather(wide_df, my_key, my_val, -col) 
long_df

# Spread the key-value pairs of long_df
spread(long_df, my_key, my_val) 

treatments <- data.frame(patient= c("X","Y","X","Y"), treatment = c("A","A","B","B"), year_mo = c("2010-10","2010-10","2012-08","2012-08"), response = c(1,4,2,5))

# Separate year_mo into two columns 
treatments_sep<-separate(treatments, year_mo, c("year", "month")) 
treatments_sep

# Unite year and month to form year_mo column 
unite(treatments_sep, year_mo, year, month) 

```


### Practice



```{r}
library(readr)
bmi <- read_csv("data/bmi_clean.csv")

# Apply gather() to bmi and save the result as bmi_long
bmi_long <- gather(bmi,year, bmi_val, -Country)

# View the first 8 rows of the result
head(bmi_long, n=8)
```


```{r}
# Apply spread() to bmi_long
bmi_wide <- spread(bmi_long, year, bmi_val)

# View the head of bmi_wide
head(bmi_long)
head(bmi_wide)
```



```{r eval=FALSE}

# Apply separate() to bmi_cc
bmi_cc_clean <- separate(bmi_cc, col = Country_ISO, into = c("Country", "ISO"), sep = "/")

# Print the head of the result
head(bmi_cc_clean)


# Apply unite() to bmi_cc_clean
bmi_cc <- unite(bmi_cc_clean, Country_ISO, Country, ISO, sep = "-")

# View the head of the result
head(bmi_cc)
```



```{r}
library(readr)
census <- read_csv("data/census-retail.csv")

# View the head of census
head(census)

# Gather the month columns
census2 <- gather(census,month,amount,-YEAR) 

# Arrange rows by YEAR using dplyr's arrange
library("dplyr")
census2_arr <- arrange(census2, YEAR)

# View first 8 rows of census2
head(census2_arr,n=8)
```



```{r}
# View first 8 rows of census_long
head(census,n=8)
census_long <- census2_arr
census_long$type <- factor(c(rep("MED", nrow(census_long)/3),rep("HIGH", nrow(census_long)/3),rep("LOW", nrow(census_long)/3)))

# Spread the type column
census_long2 <- spread(census_long,type,amount)

# View first 8 rows of census_long2
head(census_long2,n=8)
tail(census_long2,n=8)
```




```{r eval=FALSE}
# View the head of census_long3
head(census_long3)

# Separate the yr_month column into two
census_long4 <- separate(census_long3,yr_month, into = c("year","month"))

# View the first 6 rows of the result
head(census_long4, n = 6)
```

