---
title: 'Datacamp_Importing & Cleaning Data in R: Case Studies__MBTA Ridership Data'
author: "dizhen"
date: "2019/4/5"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Using readxl


```{r}
# Load readxl
library(readxl)

# Import mbta.xlsx and skip first row: mbta
mbta<-read_excel("data/mbta.xlsx",skip = 1)
```

Examining the data


```{r}
# View the structure of mbta
str(mbta)

# View the first 6 rows of mbta
head(mbta, n=6)

# View a summary of mbta
summary(mbta)
```

Removing unnecessary rows and columns


```{r}
# Remove rows 1, 7, and 11 of mbta: mbta2
mbta2 <- mbta[-c(1,7,11),]

# Remove the first column of mbta2: mbta3
mbta3 <- mbta2[,-1]
```

Observations are stored in columns



```{r}
# Load tidyr
library(tidyr)

# Gather columns of mbta3: mbta4
mbta4 <- gather(mbta3, month,thou_riders,-mode)

# View the head of mbta4
head(mbta4)
```

Type conversions


```{r}
# Coerce thou_riders to numeric
mbta4$thou_riders <- as.numeric(mbta4$thou_riders)
```

Variables are stored in both rows and columns

```{r}
# Spread the contents of mbta4: mbta5
mbta5 <- spread(mbta4, mode,thou_riders)

# View the head of mbta5
head(mbta5)
```

Separating columns



```{r}
# View the head of mbta5
head(mbta5)

# Split month column into month and year: mbta6
mbta6 <- separate(mbta5,month,c("year","month"))

# View the head of mbta6
head(mbta6)
```


Do your values seem reasonable?


```{r}
# View a summary of mbta6
summary(mbta6)

# Generate a histogram of Boat column
hist(mbta6$Boat)
```

Dealing with entry error
```{r}
# Find the row number of the incorrect value: i
i <- which(mbta6$Boat > 15)

# Replace the incorrect value with 4
mbta6$Boat[i] <- 4

# Generate a histogram of Boat column
hist(mbta6$Boat)

# # Look at Boat and Trackless Trolley ridership over time (don't change)
# ggplot(mbta_boat, aes(x = month, y = thou_riders, col = mode)) +  geom_point() + 
#   scale_x_discrete(name = "Month", breaks = c(200701, 200801, 200901, 201001, 201101)) + 
#   scale_y_continuous(name = "Avg Weekday Ridership (thousands)")
# 
# # Look at all T ridership over time (don't change)
# ggplot(mbta_all, aes(x = month, y = thou_riders, col = mode)) + geom_point() + 
#   scale_x_discrete(name = "Month", breaks = c(200701, 200801, 200901, 201001, 201101)) +  
#   scale_y_continuous(name = "Avg Weekday Ridership (thousands)")
```

