---
title: 'Datacamp_Importing & Cleaning Data in R: Case Studies_Ticket Sales Data'
author: "dizhen"
date: "2019/4/5"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Importing the data


```{r}
# Import sales.csv: sales
sales <- read.csv("data/sales.csv",stringsAsFactors = FALSE)
```


```{r}
# View dimensions of sales
dim(sales)

# Inspect first 6 rows of sales
head(sales,n = 6)

# View column names of sales
names(sales)
```

Summarizing the data

```{r}
# Look at structure of sales
str(sales)

# View a summary of sales
summary(sales)

# Load dplyr
library(dplyr)

# Get a glimpse of sales
glimpse(sales)
```

Removing redundant info


```{r}
# Remove the first column of sales: sales2
sales2 <- sales[, -1]
```

Information not worth keeping


```{r}
# Define a vector of column indices: keep
keep <-c(5:30)

# Subset sales2 using keep: sales3
sales3 <- subset(sales2,select=keep)
```

Separating columns


```{r}
# Load tidyr
library(tidyr)

# Split event_date_time: sales4
sales4 <- separate(sales3, event_date_time,
                   c("event_dt","event_time"), sep = " ")

# Split sales_ord_create_dttm: sales5
sales5 <-separate(sales4,sales_ord_create_dttm,c("ord_create_dt","ord_create_time"),sep = " ")
```

Dealing with warnings


```{r}
# Define an issues vector
issues <- c(2516, 3863, 4082, 4183)

# Print values of sales_ord_create_dttm at these indices
sales3$sales_ord_create_dttm[issues]

# Print a well-behaved value of sales_ord_create_dttm
sales3$sales_ord_create_dttm[2517]
```

Identifying dates


```{r}
# Load stringr
library(stringr)

# Find columns of sales5 containing "dt": date_cols
date_cols <- str_detect(names(sales5),"dt")

# Load lubridate
library(lubridate)

# Coerce date columns into Date objects
sales5[, date_cols] <- lapply(sales5[,date_cols], ymd)
```

More warnings!

```{r}
# Find date columns (don't change)
date_cols <- str_detect(names(sales5), "dt")

# Create logical vectors indicating missing values (don't change)
missing <- lapply(sales5[, date_cols], is.na)

# Create a numerical vector that counts missing values: num_missing
num_missing <- sapply(missing,sum)

# Print num_missing
num_missing
```

Combining columns

```{r}
# Combine the venue_city and venue_state columns  
sales6 <- unite(sales5,venue_city_state,venue_city,venue_state,sep = ', ')

# View the head of sales6
head(sales6)
```

