---
title: "Datacamp_Introduction_to_Tidyverse__Data_wrangling"
author: "dizhen"
date: "2019/4/3"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The gapminder dataset

```{r}
# Load the gapminder package
# install.packages("gapminder")
# library(gapminder)
gapminder <- read.table(file = 'data/gapminder.tsv', sep = '\t', header = TRUE)

# Load the dplyr package
library(dplyr)
library(tidyverse)

# Look at the gapminder dataset
head(gapminder)
str(gapminder)
```


## The filter verb

filter() subsets observations

```{r}
# Filtering for one year
gapminder %>% 
  filter(year == 2007) %>% head()
```
```{r}

# Filtering for one country
gapminder %>% 
  filter(country == "United States") %>% head()

```

```{r}
# Filtering for two variables
gapminder %>% 
  filter(year == 2007, country == "United States") %>% head()
```
```{r}

```


### Practice

```{r}

# Filter the gapminder dataset for the year 1957
gapminder %>% filter(year == 1957) %>% head()
```


```{r}
# Filter for China in 2002
gapminder %>% filter(year == 2002, country == 'China') %>% head()
```

## The arrange verb

arrange() sorts a table based on a variable

```{r}
gapminder %>% 
  arrange(gdpPercap) %>% head()

# sort in descending order
gapminder %>% 
  arrange(desc(gdpPercap)) %>% head()
```
```{r}
gapminder %>% 
  filter(year == 2007) %>% 
  arrange(desc(gdpPercap)) %>% head()
```

### Practice


```{r}
# Sort in ascending order of lifeExp
gapminder %>% arrange(lifeExp) %>% head()

# Sort in descending order of lifeExp
gapminder %>% arrange(desc(lifeExp)) %>% head()
```


```{r}
# Filter for the year 1957, then arrange in descending order of population
gapminder %>% filter(year == 1957) %>% arrange(desc(pop)) %>% head()
```

## The mutate verb

mutate changes or odds variables

```{r}
# change a variable
gapminder %>% mutate(pop = pop / 1000000) %>% head()

# add a new variable
gapminder %>% mutate(gdp = gdpPercap * pop)

```
```{r}
# Combining verbs
gapminder %>% 
  mutate(gdp = gdpPercap * pop) %>% 
  filter(year == 2007) %>% 
  arrange(desc(gdp))
```

### Practice


```{r}
# Use mutate to change lifeExp to be in months
gapminder %>% mutate(lifeExp = lifeExp * 12) %>% head()

# Use mutate to create a new column called lifeExpMonths
gapminder %>% mutate(lifeExpMonths = lifeExp * 12) %>% head()

```



```{r}

# Filter, mutate, and arrange the gapminder dataset
gapminder %>%
  filter(year == 2007) %>%
  mutate(lifeExpMonths = 12 * lifeExp) %>%
  arrange(desc(lifeExpMonths)) %>% head()
```

