---
title: "Datacamp_Introduction_to_Tidyverse_Data visualization"
author: "dizhen"
date: "2019/4/3"
output:
  pdf_document: default
  html_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Visualizing with ggplot2

```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
gapminder <- read.table(file = 'data/gapminder.tsv', sep = '\t', header = TRUE)
gapminder_2007 <- gapminder %>% 
  filter(year == 2007) 

```

### Practice

```{r}
# Create gapminder_1952
gapminder_1952 <- gapminder %>% filter(year == 1952) 

```


Comparing population and GDP per capita

```{r}

gapminder_1952 <- gapminder %>%
  filter(year == 1952)

# Change to put pop on the x-axis and gdpPercap on the y-axis
ggplot(gapminder_1952, aes(x = pop, y = gdpPercap)) +
  geom_point()
```


Comparing population and life expectancy


```{r}

gapminder_1952 <- gapminder %>%
  filter(year == 1952)

# Create a scatter plot with pop on the x-axis and lifeExp on the y-axis
ggplot(gapminder_1952, aes(x = pop, y = lifeExp)) + geom_point()
```


## Log scales

```{r}
# ggplot(gapminder_2007, aes(x = gdpPerCap, y = lifeExp)) +
#   geom_point()

ggplot(gapminder_2007, aes(x = gdpPercap, y = lifeExp)) + 
  geom_point() +
  scale_x_log10()
```

### Practice



```{r}

gapminder_1952 <- gapminder %>%
  filter(year == 1952)

# Change this plot to put the x-axis on a log scale
ggplot(gapminder_1952, aes(x = pop, y = lifeExp)) +
  geom_point()+ scale_x_log10()

```


```{r}

gapminder_1952 <- gapminder %>%
  filter(year == 1952)

# Scatter plot comparing pop and gdpPercap, with both axes on a log scale
ggplot(gapminder_1952,aes(x = pop, y = gdpPercap)) + geom_point()+ scale_y_log10()+scale_x_log10()
```


```{r}

gapminder_1952 <- gapminder %>%
  filter(year == 1952)

# Scatter plot comparing pop and lifeExp, with color representing continent
ggplot(gapminder_1952, aes(x = pop, y = lifeExp, color = continent)) + geom_point() + scale_x_log10()
```



```{r}

gapminder_1952 <- gapminder %>%
  filter(year == 1952)

# Add the size aesthetic to represent a country's gdpPercap
ggplot(gapminder_1952, aes(x = pop, y = lifeExp, color = continent,size = gdpPercap)) +
  geom_point() +
  scale_x_log10()
```



```{r}

gapminder_1952 <- gapminder %>%
  filter(year == 1952)

# Scatter plot comparing pop and lifeExp, faceted by continent
ggplot(gapminder_1952,aes(x = pop, y = lifeExp)) + geom_point() + scale_x_log10() + facet_wrap(~continent)
```



```{r}

# Scatter plot comparing gdpPercap and lifeExp, with color representing continent
# and size representing population, faceted by year
ggplot(gapminder,aes(x = gdpPercap, y = lifeExp,color = continent,size = pop)) + geom_point() + scale_x_log10() + facet_wrap(~year) 
```

