---
title: Foundations of Functional Programming with purrr_Simplifying Iteration and
  Lists With purrr
author: "dizhen"
date: "5/12/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The power of iteration

```{r}
# setwd("D:/git/Datacamp--r/Datacamp/_Foundations of Functional Programming with purrr/")
dir <- "data/"

library(readr)
files <- list("data_from_2005.csv","data_from_2004.csv",
              "data_from_2003.csv","data_from_2002.csv",
              "data_from_2001.csv","data_from_2000.csv",
              "data_from_1999.csv","data_from_1998.csv",
              "data_from_1997.csv","data_from_1996.csv",
              "data_from_1995.csv","data_from_1994.csv",
              "data_from_1993.csv","data_from_1992.csv",
              "data_from_1991.csv","data_from_1990.csv")
# Initialize list
all_files <- list()

# For loop to read files into a list
for(i in seq_along(files)){
  all_files[[i]] <- read_csv(file = paste(dir, files[[i]], sep = ""))
}

# Output size of list object
length(all_files)
```
```{r}
# Load purrr library
library(purrr)
files1 <- paste(dir, files,sep = "")
# Use map to iterate
all_files_purrr <- map(files1, read_csv)

# Output size of list object
length(all_files_purrr)
```

```{r}
list1 <- c("1","2","3","4")
list_of_df <- list(list1, list1, list1, list1,list1,
                   list1, list1, list1, list1,list1)

# Check the class type of the first element
class(list_of_df[[1]])

# Change each element from a character to a number
for(i in seq_along(list_of_df)){
    list_of_df[[i]] <- as.numeric(list_of_df[[i]])
}

# Check the class type of the first element
class(list_of_df[[1]])

# Print out the list
list_of_df
```

```{r}
# Check the class type of the first element
class(list_of_df[[1]])  

# Change each character element to a number
list_of_df <- map(list_of_df, as.numeric)

# Check the class type of the first element again
class(list_of_df[[1]])

# Print out the list
list_of_df
```


## Subsetting lists; it's not that hard!
```{r}
# Load repurrrsive package, to get access to the wesanderson dataset
library(repurrrsive)

# Load wesanderson dataset
data(wesanderson)

# Get structure of first element in wesanderson
str(wesanderson)

# Get structure of GrandBudapest element in wesanderson
str(wesanderson$GrandBudapest)
```

```{r}

# Third element of the first wesanderson vector
wesanderson[["GrandBudapest"]][3]

# Fourth element of the GrandBudapest wesanderson vector
wesanderson$GrandBudapest[4]

# Subset the first element of the sw_films data
sw_films[[1]]

# Subset the first element of the sw_films data, title column 
sw_films[[1]]$title
```

## The many flavors of map()

1. map(list, function)

2. map(list, ~function(.x))


```{r}
# Map over wesanderson, and determine the length of each element
map(wesanderson, ~length(.x))

# Map over wesanderson and determine the length of each element
map(wesanderson, length)

# Create a numcolors column and fill with length of each wesanderson element
data.frame(numcolors = map_dbl(wesanderson, ~length(.x)))

```




